-- Complete snapshot of the Bundesagentur für Arbeit "Ausbildungsberufe A-Z"
-- catalog, retrieved from the official source on 2026-09-14:
-- https://www.arbeitsagentur.de/bildung/berufe-und-wege/berufe-a-bis-z
--
-- The source currently lists 514 supported professions. external_code stores
-- the numeric BERUFENET profession identifier for the 452 entries whose source
-- link targets one stable /beruf/{id} page; umbrella entries that link to a
-- BERUFENET search result retain NULL rather than inventing an identifier.

insert into public.profession_catalog (external_code, name_de) values
  ('6327', 'Agrarwirtschaftlich-technische/r Assistent/in'),
  ('9063', 'Altenpflegehelfer/in'),
  ('51027', 'Anästhesietechnische/r Assistent/in'),
  ('33209', 'Änderungsschneider/in'),
  ('29047', 'Anlagenmechaniker/in'),
  ('15164', 'Anlagenmechaniker/in - Sanitär-, Heizungs- und Klimatechnik'),
  ('8603', 'Artist/in'),
  ('4303', 'Asphaltbauer/in'),
  ('10186', 'Assistent/in - Ernährung und Versorgung'),
  ('14616', 'Assistent/in - Gesundheits- und Sozialwesen'),
  ('27411', 'Assistent/in - Gesundheitstourismus/-prophylaxe'),
  ('9996', 'Assistent/in - Hotelmanagement'),
  ('67663', 'Assistent/in - Informatik (allgemeine Informatik)'),
  ('7850', 'Assistent/in - Informatik (Medieninformatik)'),
  ('7848', 'Assistent/in - Informatik (Softwaretechnik)'),
  ('7743', 'Assistent/in - Informatik (technische Informatik)'),
  ('7798', 'Assistent/in - Informatik (Wirtschaftsinformatik)'),
  ('8564', 'Assistent/in - Innenarchitektur'),
  ('14532', 'Assistent/in - Maschinenbautechnik'),
  ('7020', 'Assistent/in - Medientechnik'),
  ('15424', 'Assistent/in - Produktdesign'),
  ('14497', 'Assistent/in - Technische Kommunikation'),
  ('13620', 'Assistent/in - Tourismus'),
  ('9599', 'Atem-, Sprech- und Stimmlehrer/in'),
  ('8526', 'Audio-Engineer'),
  (null, 'Aufbereitungsmechaniker/in'),
  ('2634', 'Augenoptiker/in'),
  (null, 'Ausbaufacharbeiter/in'),
  (null, 'Automatenfachmann/-frau'),
  ('6622', 'Automobilkaufmann/-frau'),
  ('3626', 'Bäcker/in'),
  ('6755', 'Bankkaufmann/-frau'),
  ('4823', 'Baugeräteführer/in'),
  ('13727', 'Baustoffprüfer/in'),
  (null, 'Bautechnische/r Konstrukteur/in'),
  ('4304', 'Bauwerksabdichter/in'),
  ('27304', 'Bauwerksmechaniker/in für Abbruch und Betontrenntechnik'),
  ('134553', 'Beamter/Beamtin - Abschiebungshaftvollzugsdienst (mittlerer nichttechnischer Dienst)'),
  ('35301', 'Beamter/Beamtin - Allgemeine Innere Verwaltung (mittlerer nichttechnischer Dienst)'),
  ('13987', 'Beamter/Beamtin - Archivdienst (mittlerer Dienst)'),
  ('7937', 'Beamter/Beamtin - Auswärtiger Dienst (mittlerer Dienst)'),
  ('6815', 'Beamter/Beamtin - Bundesbank (mittlerer Bankdienst)'),
  ('7928', 'Beamter/Beamtin - Bundesnachrichtendienst (mittlerer nichttechnischer Dienst)'),
  ('15368', 'Beamter/Beamtin - Fernmelde- und Elektronischen Aufklärung des Bundes (mittlerer technischer Dienst)'),
  ('8176', 'Beamter/Beamtin - Feuerwehrtechnischer Dienst (mittlerer technischer Dienst)'),
  ('7942', 'Beamter/Beamtin - Justizdienst (mittlerer nichttechnischer Dienst)'),
  ('8271', 'Beamter/Beamtin - Justizvollzugsdienst (mittlerer nichttechnischer Dienst)'),
  ('13892', 'Beamter/Beamtin - Sozialverwaltung (mittlerer Dienst)'),
  ('7941', 'Beamter/Beamtin - Steuerverwaltung (mittlerer nichttechnischer Dienst)'),
  ('14954', 'Beamter/Beamtin - Verfassungsschutz (mittlerer Dienst)'),
  ('7935', 'Beamter/Beamtin - Wehrverwaltung (mittlerer nichttechnischer Dienst)'),
  ('5856', 'Beamter/Beamtin - Wetterdienst (mittlerer nichttechnischer Dienst)'),
  ('7943', 'Beamter/Beamtin - Zolldienst (mittlerer Dienst)'),
  ('2153', 'Behälter- und Apparatebauer/in'),
  ('5924', 'Bekleidungstechnische/r Assistent/in'),
  (null, 'Berg- und Maschinenmann/-frau'),
  (null, 'Bergbautechnologe/-technologin'),
  ('7342', 'Berufspilot/in (CPL (A))'),
  ('7344', 'Berufspilot/in - Hubschrauber (CPL (H))'),
  ('13794', 'Berufskraftfahrer/in'),
  ('15577', 'Bestattungsfachkraft'),
  ('3980', 'Beton- und Stahlbetonbauer/in'),
  ('13747', 'Betonfertigteilbauer/in'),
  ('7285', 'Binnenschiffer/in'),
  ('136115', 'Binnenschifffahrtskapitän/in'),
  ('6322', 'Biologielaborant/in'),
  ('2710', 'Biologiemodellmacher/in'),
  ('6315', 'Biologisch-technische/r Assistent/in'),
  ('15144', 'Bodenleger/in'),
  ('2674', 'Bogenmacher/in'),
  (null, 'Bootsbauer/in'),
  ('4539', 'Böttcher/in'),
  ('3789', 'Brauer/in und Mälzer/in'),
  ('3813', 'Brenner/in'),
  ('4201', 'Brunnenbauer/in'),
  ('90590', 'Buchbinder/in'),
  ('13749', 'Buchhändler/in'),
  ('2443', 'Büchsenmacher/in'),
  (null, 'Bühnenmaler/in und Bühnenplastiker/in'),
  ('8409', 'Bühnentänzer/in'),
  ('130315', 'Bürsten- und Pinselmacher/in'),
  ('13809', 'Chemielaborant/in'),
  ('1169', 'Chemielaborjungwerker/in'),
  ('1143', 'Chemikant/in'),
  ('5793', 'Chemisch-technische/r Assistent/in'),
  ('2436', 'Chirurgiemechaniker/in'),
  ('129406', 'Dachdecker/in'),
  ('14557', 'Designer/in - angewandte Formgebung, Schmuck und Gerät'),
  ('14326', 'Designer/in - Foto'),
  ('14217', 'Designer/in - Grafik'),
  ('13968', 'Designer/in - Kommunikationsdesign'),
  ('8459', 'Designer/in - Medien'),
  ('14319', 'Designer/in - Mode'),
  ('3814', 'Destillateur/in'),
  ('8899', 'Diätassistent/in'),
  ('142441', 'Disponent/in - Integrierte Leitstelle'),
  (null, 'Drechsler/in (Elfenbeinschnitzer/in)'),
  ('6712', 'Drogist/in'),
  ('2610', 'Edelsteinfasser/in'),
  (null, 'Edelsteinschleifer/in'),
  ('136201', 'Eisenbahner/in - Betriebsdienst - Lokführer/in und Transport'),
  ('136199', 'Eisenbahner/in - Zugverkehrssteuerung'),
  ('2774', 'Elektroanlagenmonteur/in'),
  ('134713', 'Elektroniker/in - Automatisierungs- und Systemtechnik'),
  ('15630', 'Elektroniker/in - Automatisierungstechnik'),
  ('15623', 'Elektroniker/in - Betriebstechnik'),
  ('15636', 'Elektroniker/in - Energie- und Gebäudetechnik'),
  ('134715', 'Elektroniker/in - Gebäudesystemintegration'),
  ('15621', 'Elektroniker/in - Gebäude- und Infrastruktursysteme'),
  ('15632', 'Elektroniker/in - Geräte und Systeme'),
  ('122382', 'Elektroniker/in - Informations- und Systemtechnik'),
  ('134719', 'Elektroniker/in - Maschinen und Antriebstechnik (BBiG)'),
  ('134718', 'Elektroniker/in - Maschinen und Antriebstechnik (HwO)'),
  ('5502', 'Elektrotechnische/r Assistent/in'),
  ('8369', 'Ensembleleiter/in'),
  ('8779', 'Ergotherapeut/in'),
  ('9162', 'Erzieher/in'),
  ('9106', 'Erzieher/in - Jugend- und Heimerziehung'),
  ('4390', 'Estrichleger/in'),
  ('100809', 'Fachangestellte/r - Arbeitsmarktdienstleistungen'),
  ('9496', 'Fachangestellte/r - Bäderbetriebe'),
  ('35268', 'Fachangestellte/r - Markt- und Sozialforschung'),
  (null, 'Fachangestellte/r - Medien- und Informationsdienste'),
  (null, 'Fachinformatiker/in'),
  ('35009', 'Fachkraft - Agrarservice'),
  ('50978', 'Fachkraft - Beauty und Wellness'),
  ('15085', 'Fachkraft - Fahrbetrieb'),
  ('3820', 'Fachkraft - Fruchtsafttechnik'),
  ('136126', 'Fachkraft - Gastronomie'),
  ('34996', 'Fachkraft - Hafenlogistik'),
  ('57895', 'Fachkraft - Holz- und Bautenschutzarbeiten'),
  ('35021', 'Fachkraft - Hygieneüberwachung'),
  ('33362', 'Fachkraft - Kurier-, Express- und Postdienstleistungen'),
  ('136119', 'Fachkraft - Küche'),
  ('27448', 'Fachkraft - Lagerlogistik'),
  ('3898', 'Fachkraft - Lebensmitteltechnik'),
  ('126792', 'Fachkraft - Lederherstellung und Gerbereitechnik'),
  ('90009', 'Fachkraft - Lederverarbeitung'),
  ('129419', 'Fachkraft - Medizinprodukteaufbereitung'),
  (null, 'Fachkraft - Metalltechnik'),
  ('34980', 'Fachkraft - Möbel-, Küchen- und Umzugsservice'),
  ('14463', 'Fachkraft - Schutz und Sicherheit'),
  ('14374', 'Fachkraft - Straßen- und Verkehrstechnik'),
  ('129457', 'Fachkraft - Veranstaltungstechnik'),
  ('14376', 'Fachkraft - Wasserwirtschaft'),
  ('27539', 'Fachlagerist/in'),
  ('9387', 'Fachlehrkraft - musisch-technische Fächer'),
  ('136125', 'Fachmann/-frau - Restaurants und Veranstaltungsgastronomie'),
  ('9997', 'Fachmann/-frau - Systemgastronomie'),
  ('29092', 'Fachpraktiker/in für Anlagenmechaniker SHK (§66 BBiG/§42r HwO)'),
  ('3627', 'Fachpraktiker/in für Bäcker (§66 BBiG/§42r HwO)'),
  ('1302', 'Fachpraktiker/in für Buchbinderei (§66 BBiG/§42r HwO)'),
  ('7883', 'Fachpraktiker/in für Büromanagement (§66 BBiG/§42r HwO)'),
  ('136258', 'Fachpraktiker/in für Bürstenherstellung (§66 BBiG/§42r HwO)'),
  ('132092', 'Fachpraktiker/in für Dachdecker (§66 BBiG/§42r HwO)'),
  ('124466', 'Fachpraktiker/in für Dialogmarketing (§66 BBiG/§42r HwO)'),
  ('2739', 'Fachpraktiker/in für Elektroniker (§66 BBiG/§42r HwO)'),
  ('2858', 'Fachpraktiker/in für elektronische Geräte und Systeme (§66 BBiG/§42r HwO)'),
  ('14969', 'Fachpraktiker/in für Fahrzeugpflege (§66 BBiG/§42r HwO)'),
  ('3673', 'Fachpraktiker/in für Fleischer (§66 BBiG/§42r HwO)'),
  ('134513', 'Fachpraktiker/in für Friseur (§66 BBiG/§42r HwO)'),
  ('14867', 'Fachpraktiker/in für Gebäudereiniger (§66 BBiG/§42r HwO)'),
  ('138818', 'Fachpraktiker/in für Hauswirtschaft und personenorientierte Serviceleistungen (§66 BBiG/§42r HwO)'),
  ('3946', 'Fachpraktiker/in für Hochbaufacharbeiter (§66 BBiG/§42r HwO)'),
  ('4463', 'Fachpraktiker/in für Holzverarbeitung (§66 BBiG/§42m HwO)'),
  ('129285', 'Fachpraktiker/in für Industriemechanik (§66 BBiG/§42r HwO)'),
  ('34976', 'Fachpraktiker/in für IT Systemelektronik (§66 BBiG/§42r HwO)'),
  ('137038', 'Fachpraktiker/in für IT Systemintegration (§66 BBiG/§42r HwO)'),
  ('2180', 'Fachpraktiker/in für Karosserie- und Fahrzeugbaumechanik (§66 BBiG/§42r HwO)'),
  ('2376', 'Fachpraktiker/in für Kfz-Mechatroniker (§66 BBiG/§42r HwO)'),
  ('119628', 'Fachpraktiker/in für Konstruktionsmechanik (§66 BBiG/§42r HwO)'),
  ('10254', 'Fachpraktiker/in für Kreislauf- und Abfallwirtschaft (§66 BBiG/§42r HwO)'),
  ('4708', 'Fachpraktiker/in für Lagerlogistik (§66 BBiG/§42r HwO)'),
  ('94629', 'Fachpraktiker/in für Land- und Baumaschinenmechatronik (§66 BBiG/§42r HwO)'),
  ('487', 'Fachpraktiker/in für Landwirt (§66 BBiG/§42r HwO)'),
  ('4585', 'Fachpraktiker/in für Maler und Lackierer (§66 BBiG/§42r HwO)'),
  ('130180', 'Fachpraktiker/in für Medientechnologie Druck (§66 BBiG/§42r HwO)'),
  ('1495', 'Fachpraktiker/in für Medientechnologie Druckverarbeitung (§66 BBiG/§42r HwO)'),
  ('2261', 'Fachpraktiker/in für Metallbau (§66 BBiG/§42r HwO)'),
  ('2997', 'Fachpraktiker/in für Metalltechnik (§66 BBiG/§42r HwO)'),
  ('77408', 'Fachpraktiker/in für Möbel-, Küchen- und Umzugsservice (§66 BBiG/§42r HwO)'),
  ('134912', 'Fachpraktiker/in für Orthopädietechnik (§66 BBiG/§42r HwO)'),
  ('58313', 'Fachpraktiker/in für Pferdewirt (§66 BBiG/§42r HwO)'),
  ('129985', 'Fachpraktiker/in für Service in sozialen Einrichtungen (§66 BBiG/§42r HwO)'),
  ('6496', 'Fachpraktiker/in für Technisches Produktdesign (§66 BBiG/§42r HwO)'),
  ('10212', 'Fachpraktiker/in für Textilreiniger (§66 BBiG/§42r HwO)'),
  ('4110', 'Fachpraktiker/in für Tiefbaufacharbeiter (§66 BBiG/§42r HwO)'),
  ('119768', 'Fachpraktiker/in für Tierpflege (Heim und Pension) (§66 BBiG/§42r HwO)'),
  ('125540', 'Fachpraktiker/in für Winzer (§66 BBiG/§42r HwO)'),
  ('1802', 'Fachpraktiker/in für Zerspanungsmechanik (§66 BBiG/§42r HwO)'),
  ('2473', 'Fachpraktiker/in für Zweiradmechatroniker (§66 BBiG/§42r HwO)'),
  ('4012', 'Fachpraktiker/in im Ausbaufachwerk (§66 BBiG/§42r HwO)'),
  ('579', 'Fachpraktiker/in im Gartenbau (§66 BBiG/§42r HwO)'),
  ('10088', 'Fachpraktiker/in im Gastgewerbe (§66 BBiG/§42r HwO)'),
  ('50987', 'Fachpraktiker/in im Gebäudeservice (§66 BBiG/§42r HwO)'),
  ('138060', 'Fachpraktiker/in im Gesundheitswesen (§66 BBiG/§42r HwO)'),
  ('14818', 'Fachpraktiker/in im Nahrungsmittelverkauf (§66 BBiG/§42r HwO)'),
  ('6649', 'Fachpraktiker/in im Verkauf (§66 BBiG/§42r HwO)'),
  ('93274', 'Fachpraktiker/in für Floristik (§66 BBiG/§42r HwO)'),
  ('3747', 'Fachpraktiker/in Küche (Beikoch) (§66 BBiG/§42r HwO)'),
  ('3258', 'Fachpraktiker/in - Näherei, Schneiderei (§66 BBiG/§42r HwO)'),
  ('15326', 'Fachunteroffizier/in - Allgemeiner Fachdienst'),
  ('15336', 'Fachunteroffizier/in - Militärmusikdienst'),
  ('15332', 'Fachunteroffizier/in - Sanitätsdienst'),
  (null, 'Fachverkäufer/in - Lebensmittelhandwerk'),
  ('3009', 'Fachwerker/in - Feinwerktechnik (§66 BBiG/§42r HwO)'),
  ('27394', 'Fahrradmonteur/in'),
  ('134333', 'Fahrzeuginterieur-Mechaniker/in'),
  ('15540', 'Fahrzeuglackierer/in'),
  ('3951', 'Fassadenmonteur/in'),
  ('1123', 'Feinoptiker/in'),
  ('1946', 'Feinpolierer/in'),
  ('15145', 'Feinwerkmechaniker/in'),
  ('15330', 'Feldwebel - Allgemeiner Fachdienst'),
  ('15444', 'Feldwebel - Geoinformationsdienst'),
  ('15442', 'Feldwebel - Militärmusikdienst'),
  ('15440', 'Feldwebel - Sanitätsdienst'),
  ('15328', 'Feldwebel - Truppendienst'),
  ('2488', 'Fertigungsmechaniker/in'),
  ('3961', 'Feuerungs- und Schornsteinbauer/in'),
  ('995', 'Figurenkeramformer/in'),
  (null, 'Fischwirt/in'),
  ('131053', 'Flachglastechnologe/-technologin'),
  ('50909', 'Flechtwerkgestalter/in'),
  ('13804', 'Fleischer/in'),
  ('4325', 'Fliesen-, Platten- und Mosaikleger/in'),
  ('680', 'Florist/in'),
  ('123282', 'Fluggerätelektroniker/in'),
  (null, 'Fluggerätmechaniker/in'),
  ('9405', 'Förderlehrkraft'),
  ('727', 'Forstwirt/in'),
  ('76789', 'Fotograf/in'),
  ('58383', 'Fotomedienfachmann/-frau'),
  ('6461', 'Foto- und medientechnische/r Assistent/in'),
  ('7989', 'Fremdsprachenkorrespondent/in'),
  ('9910', 'Friseur/in'),
  (null, 'Gärtner/in'),
  ('14869', 'Gamedesigner/in'),
  ('9999', 'Gastronomische/r Assistent/in'),
  ('10236', 'Gebäudereiniger/in'),
  ('2673', 'Geigenbauer/in'),
  ('9898', 'Gemeindediakon/in'),
  ('77494', 'Geomatiker/in'),
  ('4066', 'Gerüstbauer/in'),
  ('137579', 'Gestalter/in - immersive Medien'),
  ('27542', 'Gestalter/in - visuelles Marketing'),
  ('6515', 'Gestaltungstechnische/r Assistent/in'),
  ('30191', 'Gesundheits- und Krankenpflegehelfer/in'),
  ('126847', 'Gießereimechaniker/in'),
  ('4653', 'Glas- und Porzellanmaler/in'),
  ('1077', 'Glasapparatebauer/in'),
  (null, 'Glasbläser/in'),
  (null, 'Glaser/in'),
  ('1048', 'Glasmacher/in'),
  (null, 'Glasveredler/in'),
  ('4144', 'Gleisbauer/in'),
  (null, 'Gold- und Silberschmied/in'),
  ('129455', 'Graveur/in'),
  ('9524', 'Gymnastiklehrer/in'),
  ('7288', 'Hafenschiffer/in'),
  ('2694', 'Handzuginstrumentenmacher/in'),
  ('9077', 'Haus- und Familienpfleger/in'),
  ('133617', 'Hauswirtschafter/in'),
  ('13778', 'Heilerziehungspflegeassistent/in'),
  ('9127', 'Heilerziehungspfleger/in'),
  ('33207', 'HNO-Audiologieassistent/in'),
  (null, 'Hochbaufacharbeiter/in'),
  (null, 'Holz- und Bautenschützer/in'),
  ('29057', 'Holzbearbeitungsmechaniker/in'),
  ('1534', 'Holzbildhauer/in'),
  ('2687', 'Holzblasinstrumentenmacher/in'),
  (null, 'Holzmechaniker/in'),
  ('1566', 'Holzspielzeugmacher/in'),
  ('129408', 'Hörakustiker/in'),
  ('10009', 'Hotelfachmann/-frau'),
  ('9042', 'Hygienekontrolleur/in'),
  ('35275', 'Immobilienkaufmann/-frau'),
  (null, 'Industrieelektriker/in'),
  ('3003', 'Industriefachhelfer/in (§66 BBiG/§42r HwO)'),
  ('4279', 'Industrie-Isolierer/in'),
  ('7965', 'Industriekaufmann/-frau'),
  ('34941', 'Industriekeramiker/in Anlagentechnik'),
  ('34948', 'Industriekeramiker/in Dekorationstechnik'),
  ('34938', 'Industriekeramiker/in Modelltechnik'),
  ('34943', 'Industriekeramiker/in Verfahrenstechnik'),
  ('29055', 'Industriemechaniker/in'),
  ('134721', 'Informationselektroniker/in'),
  ('15518', 'Investmentfondskaufmann/-frau'),
  ('4280', 'Isolierfacharbeiter/in'),
  ('2927', 'IT-System-Elektroniker/in'),
  ('7924', 'Justizfachangestellte/r'),
  ('33320', 'Justizwachtmeister/in'),
  ('8589', 'Kameramann/-frau'),
  ('139142', 'Kanalbauer/in - Infrastrukturtechnik'),
  (null, 'Karosserie- und Fahrzeugbaumechaniker/in'),
  ('14517', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Betriebsinformatik'),
  ('7891', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Betriebswirtschaft'),
  ('7893', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Bürowirtschaft'),
  ('137121', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - E-Business Management'),
  ('7991', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Fremdsprachen'),
  ('7789', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Informationsverarbeitung'),
  ('7017', 'Kaufmännische/r Assistent/in/Wirtschaftsassistent/in - Medien'),
  ('7018', 'Kaufmann/-frau - audiovisuelle Medien'),
  ('123266', 'Kaufmann/-frau - Büromanagement'),
  ('35311', 'Kaufmann/-frau - Dialogmarketing'),
  ('133555', 'Kaufmann/-frau - Digitalisierungsmanagement'),
  ('130926', 'Kaufmann/-frau - E-Commerce'),
  ('6580', 'Kaufmann/-frau - Einzelhandel'),
  ('7889', 'Kaufmann/-frau - Gesundheitswesen'),
  (null, 'Kaufmann/-frau - Groß- und Außenhandelsmanagement'),
  ('136121', 'Kaufmann/-frau - Hotelmanagement'),
  ('133558', 'Kaufmann/-frau - IT-System-Management'),
  ('33364', 'Kaufmann/-frau - Kurier-, Express- und Postdienstleistungen'),
  ('35279', 'Kaufmann/-frau - Marketingkommunikation'),
  ('143179', 'Kaufmann/-frau - Mobilität und Verkehrsservice'),
  ('29441', 'Kaufmann/-frau - Spedition und Logistikdienstleistung'),
  ('33235', 'Kaufmann/-frau - Tourismus und Freizeit'),
  ('136117', 'Kaufmann/-frau - Versicherungen und Finanzanlagen'),
  ('76608', 'Keramiker/in'),
  ('126857', 'Kerzenhersteller/in und Wachsbildner/in'),
  (null, 'Klavier- und Cembalobauer/in'),
  ('2168', 'Klempner/in'),
  ('3726', 'Koch/Köchin'),
  ('3654', 'Konditor/in'),
  ('29049', 'Konstruktionsmechaniker/in'),
  ('14624', 'Kosmetiker/in (duale Ausbildung)'),
  ('9929', 'Kosmetiker/in (schulische Ausbildung)'),
  (null, 'Kraftfahrzeugmechatroniker/in'),
  (null, 'Kunststoff- und Kautschuktechnologe/-technologin'),
  ('3611', 'Kürschner/in'),
  ('6415', 'Lacklaborant/in'),
  ('124412', 'Land- und Baumaschinenmechatroniker/in'),
  ('272', 'Landwirt/in'),
  ('5879', 'Lebensmitteltechnische/r Assistent/in'),
  ('4559', 'Leichtflugzeugbauer/in'),
  ('139146', 'Leitungsbauer/in - Infrastrukturtechnik'),
  ('1088', 'Leuchtröhrenglasbläser/in'),
  ('8764', 'Logopäde/Logopädin'),
  ('6928', 'Luftverkehrskaufmann/-frau'),
  (null, 'Maler/in und Lackierer/in'),
  ('58991', 'Managementassistent/in (schulische Ausbildung)'),
  ('4664', 'Manufakturporzellanmaler/in'),
  (null, 'Maschinen- und Anlagenführer/in'),
  ('15200', 'Maskenbildner/in'),
  ('8734', 'Masseur/in und medizinische/r Bademeister/in'),
  ('27398', 'Maßschneider/in'),
  (null, 'Maßschuhmacher/in'),
  ('14087', 'Mathematisch-technische/r Assistent/in'),
  ('51029', 'Mathematisch-technische/r Softwareentwickler/in'),
  ('3938', 'Maurer/in'),
  (null, 'Mechaniker/in - Reifen- und Vulkanisationstechnik'),
  ('2868', 'Mechatroniker/in'),
  ('35283', 'Mechatroniker/in - Kältetechnik'),
  ('8533', 'Mediengestalter/in - Bild und Ton'),
  (null, 'Mediengestalter/in Digital und Print'),
  ('35281', 'Medienkaufmann/-frau Digital und Print'),
  ('90572', 'Medientechnologe/-technologin Druck'),
  ('90574', 'Medientechnologe/-technologin Druckverarbeitung'),
  ('90578', 'Medientechnologe/-technologin Siebdruck'),
  ('8343', 'Medizinische/r Dokumentationsassistent/in'),
  ('33212', 'Medizinische/r Fachangestellte/r'),
  ('9013', 'Medizinische/r Sektions- und Präparationsassistent/in'),
  ('135579', 'Medizinische/r Technologe/Technologin - Funktionsdiagnostik'),
  ('135577', 'Medizinische/r Technologe/Technologin - Laboratoriumsanalytik'),
  ('135581', 'Medizinische/r Technologe/Technologin - Radiologie'),
  ('135583', 'Medizinische/r Technologe/Technologin - Veterinärmedizin'),
  (null, 'Metall- und Glockengießer/in'),
  (null, 'Metallbauer/in'),
  (null, 'Metallbildner/in'),
  ('2665', 'Metallblasinstrumentenmacher/in'),
  ('2757', 'Mikrotechnologe/-technologin'),
  ('77248', 'Milchtechnologe/-technologin'),
  ('6342', 'Milchwirtschaftliche/r Laborant/in'),
  ('3353', 'Modist/in'),
  ('8377', 'Musiker/in - Kirchenmusik'),
  ('73829', 'Musikfachhändler/in'),
  (null, 'Naturwerksteinmechaniker/in'),
  ('7955', 'Notarfachangestellte/r'),
  ('122462', 'Notfallsanitäter/in'),
  ('34975', 'Oberflächenbeschichter/in'),
  ('35285', 'Ofen- und Luftheizungsbauer/in'),
  ('8830', 'Operationstechnische/r Assistent/in'),
  (null, 'Orgelbauer/in'),
  ('3497', 'Orthopädieschuhmacher/in'),
  ('122351', 'Orthopädietechnik-Mechaniker/in'),
  ('8769', 'Orthoptist/in'),
  ('90568', 'Packmitteltechnologe/-technologin'),
  ('78502', 'Papiertechnologe/-technologin'),
  ('4415', 'Parkettleger/in'),
  ('7957', 'Patentanwaltsfachangestellte/r'),
  ('3602', 'Pelzveredler/in'),
  ('58385', 'Personaldienstleistungskaufmann/-frau'),
  (null, 'Pferdewirt/in'),
  ('122322', 'Pflanzentechnologe/-technologin'),
  ('135349', 'Pflegeassistent/in'),
  ('143399', 'Pflegefachassistent/in / Pflegefachassistenzperson'),
  ('132173', 'Pflegefachmann/-frau'),
  ('1151', 'Pharmakant/in'),
  ('6717', 'Pharmazeutisch-kaufmännische/r Angestellte/r'),
  ('8910', 'Pharmazeutisch-technische/r Assistent/in'),
  ('5826', 'Physikalisch-technische/r Assistent/in'),
  ('6351', 'Physiklaborant/in'),
  ('8750', 'Physiotherapeut/in'),
  ('14427', 'Podologe/Podologin'),
  ('8158', 'Polizeivollzugsbeamter/-beamtin (mittlerer nichttechnischer Dienst)'),
  ('8161', 'Polizeivollzugsbeamter/-beamtin - Bundespolizei (mittlerer nichttechnischer Dienst)'),
  ('4442', 'Polster- und Dekorationsnäher/in'),
  ('4432', 'Polsterer/Polsterin'),
  ('2713', 'Präparationstechnische/r Assistent/in'),
  (null, 'Präzisionswerkzeugmechaniker/in'),
  ('8477', 'Produktgestalter/in - Textil'),
  ('34950', 'Produktionsfachkraft Chemie'),
  ('33210', 'Produktionsmechaniker/in - Textil'),
  ('67789', 'Produktionstechnologe/-technologin'),
  ('51106', 'Produktprüfer/in - Textil'),
  ('34937', 'Produktveredler/in - Textil'),
  ('130893', 'Prüftechnologe/-technologin Keramik'),
  ('4405', 'Raumausstatter/in'),
  ('4425', 'Raumausstatterwerker/in (§66 BBiG/§42r HwO)'),
  ('7959', 'Rechtsanwalts- und Notarfachangestellte/r'),
  ('7958', 'Rechtsanwaltsfachangestellte/r'),
  ('8888', 'Rettungssanitäter/in'),
  ('713', 'Revierjäger/in'),
  ('27530', 'Rollladen- und Sonnenschutzmechatroniker/in'),
  (null, 'Sattler/in'),
  ('27396', 'Schädlingsbekämpfer/in'),
  ('29471', 'Schäftemacher/in (§66 BBiG/§42r HwO)'),
  ('8412', 'Schauspieler/in'),
  (null, 'Schifffahrtskaufmann/-frau'),
  ('7273', 'Schiffsmechaniker/in'),
  ('8491', 'Schilder- und Lichtreklamehersteller/in'),
  ('2574', 'Schmuckwerker/in (§66 BBiG/§42r HwO)'),
  ('8213', 'Schornsteinfeger/in'),
  ('3513', 'Schuhfertiger/in'),
  ('2074', 'Schweißwerker/in (§66 BBiG/§42r HwO)'),
  ('3379', 'Segelmacher/in'),
  ('3045', 'Seiler/in'),
  ('35309', 'Servicefachkraft - Dialogmarketing'),
  ('33360', 'Servicefahrer/in'),
  ('6972', 'Servicekaufmann/-frau - Luftverkehr'),
  ('70148', 'Servicekraft - Schutz und Sicherheit'),
  ('9031', 'Sozialassistent/in'),
  ('9170', 'Sozialpädagogische/r Assistent/in / Kinderpfleger/in'),
  (null, 'Sozialversicherungsfachangestellte/r'),
  ('4188', 'Spezialtiefbauer/in'),
  ('2704', 'Spielzeughersteller/in'),
  ('14449', 'Sport- und Fitnesskaufmann/-frau'),
  ('15652', 'Sportassistent/in'),
  ('58343', 'Sportfachmann/-frau'),
  ('122285', 'Stanz- und Umformmechaniker/in'),
  (null, 'Steinmetz/in und Steinbildhauer/in'),
  ('7573', 'Steuerfachangestellte/r'),
  ('4105', 'Straßenbauer/in'),
  ('7194', 'Straßenwärter/in'),
  ('4248', 'Stuckateur/in'),
  ('124029', 'Süßwarentechnologe/-technologin'),
  ('14302', 'Technische/r Assistent/in - Automatisierungstechnik'),
  ('5620', 'Technische/r Assistent/in - Bautechnik'),
  ('2874', 'Technische/r Assistent/in - medizinische Gerätetechnik'),
  ('6379', 'Technische/r Assistent/in - Metallografie und Werkstoffkunde'),
  ('13625', 'Technische/r Assistent/in - naturkundliche Museen und Forschungsinstitute'),
  ('33197', 'Technische/r Assistent/in - Energietechnik'),
  ('3388', 'Technische/r Konfektionär/in'),
  (null, 'Technische/r Modellbauer/in'),
  (null, 'Technische/r Produktdesigner/in'),
  (null, 'Technische/r Systemplaner/in'),
  ('7391', 'Telefonist/in (§66 BBiG/§42r HwO)'),
  ('126794', 'Textil- und Modenäher/in'),
  ('126796', 'Textil- und Modeschneider/in'),
  (null, 'Textilgestalter/in im Handwerk'),
  ('6419', 'Textillaborant/in'),
  ('10211', 'Textilreiniger/in'),
  (null, 'Thermometermacher/in'),
  (null, 'Tiefbaufacharbeiter/in'),
  ('33214', 'Tiermedizinische/r Fachangestellte/r'),
  (null, 'Tierpfleger/in'),
  (null, 'Tierwirt/in'),
  ('4460', 'Tischler/in'),
  ('93277', 'Tourismuskaufmann/-frau (Privat- und Geschäftsreisen)'),
  ('4289', 'Trockenbaumonteur/in'),
  ('2502', 'Uhrmacher/in'),
  ('6045', 'Umweltschutztechnische/r Assistent/in'),
  ('138722', 'Umwelttechnologe/-technologin - Abwasserbewirtschaftung'),
  ('138725', 'Umwelttechnologe/-technologin - Kreislauf- und Abfallwirtschaft'),
  ('138723', 'Umwelttechnologe/-technologin - Rohrleitungsnetze und Industrieanlagen'),
  ('138721', 'Umwelttechnologe/-technologin - Wasserversorgung'),
  ('14448', 'Veranstaltungskaufmann/-frau'),
  ('4613', 'Verfahrensmechaniker/in - Beschichtungstechnik'),
  ('15146', 'Verfahrensmechaniker/in - Brillenoptik'),
  ('14318', 'Verfahrensmechaniker/in - Glastechnik'),
  (null, 'Verfahrensmechaniker/in - Steine- und Erdenindustrie'),
  (null, 'Verfahrenstechnologe/-technologin Metall'),
  (null, 'Verfahrenstechnologe/-technologin - Mühlen- und Getreidewirtschaft'),
  ('4640', 'Vergolder/in'),
  ('6628', 'Verkäufer/in'),
  (null, 'Vermessungstechniker/in'),
  (null, 'Verwaltungsfachangestellte/r'),
  ('4278', 'Wärme-, Kälte- und Schallschutzisolierer/in'),
  ('4171', 'Wasserbauer/in'),
  ('122362', 'Weintechnologe/-technologin'),
  ('76769', 'Werkfeuerwehrmann/-frau'),
  ('8010', 'Werkgehilfe/-gehilfin - Schmuckwarenindustrie, Taschen- und Armbanduhren'),
  ('126855', 'Werksteinhersteller/in'),
  (null, 'Werkstoffprüfer/in'),
  ('29051', 'Werkzeugmechaniker/in'),
  ('294', 'Winzer/in'),
  ('8317', 'Wirtschaftsübersetzer/in'),
  ('14704', 'Zahnmedizinische/r Fachangestellte/r'),
  ('2622', 'Zahntechniker/in'),
  ('29053', 'Zerspanungsmechaniker/in'),
  ('4010', 'Zimmerer/Zimmerin'),
  (null, 'Zupfinstrumentenmacher/in'),
  (null, 'Zweiradmechatroniker/in'),
  ('9015', 'Zytologieassistent/in');
