-- Seeds profession_catalog with a curated starter list of well-known German
-- Ausbildungsberufe, standing in for the full Bundesagentur für Arbeit
-- "Berufe A-Z" catalog until the official list is imported. external_code
-- is left NULL throughout — it's reserved for the BA's own identifiers,
-- which this hand-curated list doesn't have (the column already allows
-- multiple NULLs under its `unique` constraint).
--
-- Kept as its own migration, separate from the onboarding schema/RPC
-- changes, so the catalog can be corrected or extended independently.

insert into profession_catalog (name_de, category) values
  ('Industriemechaniker/-in', 'Industrie & Technik'),
  ('Mechatroniker/-in', 'Industrie & Technik'),
  ('Elektroniker/-in für Betriebstechnik', 'Industrie & Technik'),
  ('Elektroniker/-in für Energie- und Gebäudetechnik', 'Industrie & Technik'),
  ('Elektroanlagenmonteur/-in', 'Industrie & Technik'),
  ('Zerspanungsmechaniker/-in', 'Industrie & Technik'),
  ('Werkzeugmechaniker/-in', 'Industrie & Technik'),
  ('Konstruktionsmechaniker/-in', 'Industrie & Technik'),
  ('Anlagenmechaniker/-in für Sanitär-, Heizungs- und Klimatechnik', 'Industrie & Technik'),
  ('Verfahrenstechnologe/-technologin', 'Industrie & Technik'),
  ('Produktionstechnologe/-technologin', 'Industrie & Technik'),
  ('Fertigungsmechaniker/-in', 'Industrie & Technik'),
  ('Feinwerkmechaniker/-in', 'Industrie & Technik'),
  ('Metallbauer/-in', 'Industrie & Technik'),
  ('Chemikant/-in', 'Industrie & Technik'),
  ('Chemielaborant/-in', 'Industrie & Technik'),
  ('Verpackungsmittelmechaniker/-in', 'Industrie & Technik'),
  ('Technische/r Systemplaner/-in', 'Industrie & Technik'),
  ('Technische/r Produktdesigner/-in', 'Industrie & Technik'),

  ('Fachinformatiker/-in – Anwendungsentwicklung', 'IT'),
  ('Fachinformatiker/-in – Systemintegration', 'IT'),
  ('Fachinformatiker/-in – Daten- und Prozessanalyse', 'IT'),
  ('Fachinformatiker/-in – Digitale Vernetzung', 'IT'),
  ('IT-Systemelektroniker/-in', 'IT'),
  ('Kaufmann/-frau für IT-System-Management', 'IT'),
  ('Kaufmann/-frau für Digitalisierungsmanagement', 'IT'),

  ('Kaufmann/-frau für Büromanagement', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau im Groß- und Außenhandelsmanagement', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau im Einzelhandel', 'Handel & Kaufmännisches'),
  ('Verkäufer/-in', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau für Versicherungen und Finanzen', 'Handel & Kaufmännisches'),
  ('Bankkaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Immobilienkaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau für Spedition und Logistikdienstleistung', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau im E-Commerce', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau für Marketingkommunikation', 'Handel & Kaufmännisches'),
  ('Steuerfachangestellte/-r', 'Handel & Kaufmännisches'),
  ('Rechtsanwaltsfachangestellte/-r', 'Handel & Kaufmännisches'),
  ('Personaldienstleistungskaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Automobilkaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau im Gesundheitswesen', 'Handel & Kaufmännisches'),
  ('Fachkraft für Lagerlogistik', 'Handel & Kaufmännisches'),
  ('Fachlagerist/-in', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau für Dialogmarketing', 'Handel & Kaufmännisches'),
  ('Kaufmann/-frau für Kurier-, Express- und Postdienstleistungen', 'Handel & Kaufmännisches'),
  ('Veranstaltungskaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Buchhändler/-in', 'Handel & Kaufmännisches'),
  ('Verlagskaufmann/-frau', 'Handel & Kaufmännisches'),
  ('Sport- und Fitnesskaufmann/-frau', 'Handel & Kaufmännisches'),

  ('Pflegefachmann/-frau', 'Gesundheit'),
  ('Zahnmedizinische/-r Fachangestellte/-r', 'Gesundheit'),
  ('Medizinische/-r Fachangestellte/-r', 'Gesundheit'),
  ('Physiotherapeut/-in', 'Gesundheit'),
  ('Ergotherapeut/-in', 'Gesundheit'),
  ('Notfallsanitäter/-in', 'Gesundheit'),
  ('Rettungssanitäter/-in', 'Gesundheit'),
  ('Pharmazeutisch-kaufmännische/-r Angestellte/-r', 'Gesundheit'),
  ('Pharmazeutisch-technische/-r Assistent/-in', 'Gesundheit'),
  ('Diätassistent/-in', 'Gesundheit'),
  ('Hebamme/Entbindungspfleger', 'Gesundheit'),

  ('Friseur/-in', 'Handwerk'),
  ('Tischler/-in', 'Handwerk'),
  ('Maler/-in und Lackierer/-in', 'Handwerk'),
  ('Bäcker/-in', 'Handwerk'),
  ('Konditor/-in', 'Handwerk'),
  ('Fleischer/-in', 'Handwerk'),
  ('Dachdecker/-in', 'Handwerk'),
  ('Klempner/-in', 'Handwerk'),
  ('Zimmerer/Zimmerin', 'Handwerk'),
  ('Fliesen-, Platten- und Mosaikleger/-in', 'Handwerk'),
  ('Glaser/-in', 'Handwerk'),
  ('Raumausstatter/-in', 'Handwerk'),
  ('Goldschmied/-in', 'Handwerk'),
  ('Uhrmacher/-in', 'Handwerk'),
  ('Schuhmacher/-in', 'Handwerk'),
  ('Kürschner/-in', 'Handwerk'),
  ('Steinmetz/-in und Steinbildhauer/-in', 'Handwerk'),

  ('Maurer/-in', 'Bau'),
  ('Betonbauer/-in', 'Bau'),
  ('Straßenbauer/-in', 'Bau'),
  ('Kanalbauer/-in', 'Bau'),
  ('Baugeräteführer/-in', 'Bau'),
  ('Bauzeichner/-in', 'Bau'),
  ('Gerüstbauer/-in', 'Bau'),

  ('Kraftfahrzeugmechatroniker/-in', 'Kfz & Verkehr'),
  ('Zweiradmechatroniker/-in', 'Kfz & Verkehr'),
  ('Berufskraftfahrer/-in', 'Kfz & Verkehr'),
  ('Fachkraft im Fahrbetrieb', 'Kfz & Verkehr'),
  ('Luftverkehrskaufmann/-frau', 'Kfz & Verkehr'),
  ('Schifffahrtskaufmann/-frau', 'Kfz & Verkehr'),

  ('Koch/Köchin', 'Gastronomie & Hotellerie'),
  ('Hotelfachmann/-frau', 'Gastronomie & Hotellerie'),
  ('Restaurantfachmann/-frau', 'Gastronomie & Hotellerie'),
  ('Fachkraft im Gastgewerbe', 'Gastronomie & Hotellerie'),
  ('Fachmann/-frau für Systemgastronomie', 'Gastronomie & Hotellerie'),
  ('Bäckereifachverkäufer/-in', 'Gastronomie & Hotellerie'),
  ('Fleischereifachverkäufer/-in', 'Gastronomie & Hotellerie'),

  ('Mediengestalter/-in Digital und Print', 'Medien & Kreativwirtschaft'),
  ('Fotograf/-in', 'Medien & Kreativwirtschaft'),

  ('Landwirt/-in', 'Landwirtschaft & Natur'),
  ('Gärtner/-in', 'Landwirtschaft & Natur'),
  ('Forstwirt/-in', 'Landwirtschaft & Natur'),
  ('Tierpfleger/-in', 'Landwirtschaft & Natur'),
  ('Winzer/-in', 'Landwirtschaft & Natur'),
  ('Milchtechnologe/-technologin', 'Landwirtschaft & Natur'),
  ('Fischwirt/-in', 'Landwirtschaft & Natur'),

  ('Verwaltungsfachangestellte/-r', 'Öffentlicher Dienst & Bildung'),
  ('Sozialversicherungsfachangestellte/-r', 'Öffentlicher Dienst & Bildung'),
  ('Fachangestellte/-r für Bäderbetriebe', 'Öffentlicher Dienst & Bildung'),
  ('Erzieher/-in', 'Öffentlicher Dienst & Bildung'),

  ('Kosmetiker/-in', 'Dienstleistung & Sonstige'),
  ('Gebäudereiniger/-in', 'Dienstleistung & Sonstige'),
  ('Textilreiniger/-in', 'Dienstleistung & Sonstige'),
  ('Drogist/-in', 'Dienstleistung & Sonstige'),
  ('Fachkraft für Möbel-, Küchen- und Umzugsservice', 'Dienstleistung & Sonstige');
